name: Sandbox Environment Build

on:
  create:
    tags:
    - v&*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GCE_PROJECT: ${{ secrets.GCE_PROJECT }}
      GCE_SA_KEY: ${{ secrets.GCE_SA_KEY }}
    
    permissions:
        contents: 'read'
        id-token: 'write'
    
    steps:
    - uses: actions/checkout@v3
    
    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
        
    # 테라폼 적용
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.6
        
    - name: Terraform fmt
      run: terraform fmt
      
    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
    - name: Terraform Validate
      run: terraform validate -no-color
      
    - name: Terraform Plan
      run: terraform plan -no-color
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
    - name: Terraform Apply
      run: terraform apply -no-color -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    
    #정보 게시
    - name: Upload kubeconfig file
      uses: actions/upload-artifact@v2
      with:
        name: kubeconfig
        path: kubeconfig